export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const GET_CONTACTS = "GET_CONTACTS";

export const CHANGE_FILTER = "CHANGE_FILTER";

export const CONTACT_REQUEST_START = "CONTACT_REQUEST_START";
export const CONTACT_REQUEST_SUCSSES = "CONTACT_REQUEST_SUCSSES";
export const GET_CONTACTS_START = "GET_CONTACTS_START";
export const GET_CONTACTS_SUCSSES = "GET_CONTACTS_SUCSSES";
export const DELETE_CONTACTS_START = "DELETE_CONTACTS_START";
export const DELETE_CONTACTS_SUCSSES = "DELETE_CONTACTS_SUCSSES";

export const POST_CONTACT_ERROR = "POST_CONTACT_ERROR";
export const POST_CONTACT_ERROR_RESET = "POST_CONTACT_ERROR_RESET";
export const GET_CONTACT_ERROR = "GET_CONTACT_ERROR";
export const GET_CONTACT_ERROR_RESET = "GET_CONTACT_ERROR_RESET";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";
export const DELETE_CONTACT_ERROR_RESET = "DELETE_CONTACT_ERROR_RESET";
